image:
  file: Dockerfile
ports:
- port: 5000
- port: 5900
  onOpen: ignore
- port: 6080
  onOpen: open-browser
tasks:
- name: install
  command: pipenv install --dev &&
    pipenv shell
- command: open /workspace/flask-admin-starter/upload/machine-learning-ex1/ex1.pdf && exit
- name: octave-cli
  command: cd /workspace/flask-admin-starter/upload/machine-learning-ex1/ex1 && octave
- name: octave-gui
  command: cd /workspace/flask-admin-starter/upload/machine-learning-ex1/ex1 && octave --force-gui

vscode:
  extensions:
    - toasty-technologies.octave@0.0.3:dOpHm4yHotFWxEeHur9L7A==