image:
  file: Dockerfile
ports:
- port: 5000
- port: 5900
  onOpen: ignore
- port: 6080
  onOpen: open-preview
tasks:
- command: open /workspace/coursera-machine-learning-dev/machine-learning-ex1/ex1.pdf && exit
- name: octave-cli
  command: cd /workspace/coursera-machine-learning-dev/ex1 && octave
- name: octave-gui
  command: cd /workspace/coursera-machine-learning-dev/ex1 && octave --force-gui

vscode:
  extensions:
    - toasty-technologies.octave@0.0.3:dOpHm4yHotFWxEeHur9L7A==