image:
  file: Dockerfile
ports:
- port: 5900
  onOpen: ignore
- port: 6080
  onOpen: open-preview
tasks:
- name: octave-gui
  command: cd /workspace/machine-learning-online-dev && octave --force-gui
- name: octave-cli
  command: cd /workspace/machine-learning-online-dev && octave

vscode:
  extensions:
    - toasty-technologies.octave@0.0.3:dOpHm4yHotFWxEeHur9L7A==